# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
    tty: true
    ports:
      - ${SERVER_PORT}:8080
        
  validate:
    depends_on:
      app:
        condition: service_healthy
    profiles: [validate]
    build:
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache bash curl libxml2-utils
    environment:
      ENDPOINT: app:8080
      TMPFILE: /val/validation/validate.xml
    entrypoint: ./validate.sh
    working_dir: /val/validation
    volumes:
      - ./:/val
        
volumes:
  pkg:
