# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

- origin: [BIKE_SHARING_BOLZANO]
  id: "Municipality of Bolzano bikesharing"
  name: Municipality of Bolzano
  email: urp@comune.bolzano.it
  phone: 0471997111
  url: https://opencity.comune.bolzano.it/Servizi/Bike-Sharing-Bici-Bolzano
  street: Vicolo Gumer 7
  town: Bolzano
  postcode: 39100
  country: Italy
  
- origin: [BIKE_SHARING_MERANO]
  id: "Municipality of Merano bikesharing"
  name: Municipality of Merano
  email: info@comune.merano.bz.it
  phone: 0473250111
  url: https://www.comune.merano.bz.it/it/Bikesharing
  street: Via Portici 192
  town: Merano
  postcode: 39012
  country: Italy
  
- origin: [BIKE_SHARING_PAPIN]
  id: Papin Sport
  name: Papin Sport
  email: info@papinsport.com
  phone: 0474913450
  url: https://www.papinsport.com/rent-a-bike/
  street: Via Freising 9
  town: San Candido
  postcode: 39038
  country: Italy
  
- origin: [HAL-API]
  id: Car Sharing Alto Adige
  name: Car Sharing Alto Adige
  email: info@carsharing.bz.it
  phone: 0471061319
  url: https://www.carsharing.bz.it/it/
  street: Via Beda Weber 1
  town: Bolzano
  postcode: 39100
  country: Italy
  
- origin: [FAMAS]
  id: "Municipality of Bolzano parking"
  name: Municipality of Bolzano
  email: urp@comune.bolzano.it
  phone: 0471997111
  url: https://opencity.comune.bolzano.it/Documenti-e-dati/Documenti-tecnici-di-supporto/Parcheggiare-in-citta
  street: Vicolo Gumer 7
  town: Bolzano
  postcode: 39100
  country: Italy
  
- origin: [Municipality Merano]
  id: "Municipality of Merano parking"
  name: Municipality of Merano
  email: info@comune.merano.bz.it
  phone: 0473250111
  url: https://www.comune.merano.bz.it/it/Parcheggi
  street: Via Portici 192
  town: Merano
  postcode: 39012
  country: Italy
  
- origin: [FBK-Trento]
  id: Municipality of Trento
  name: Municipality of Trento
  email: comurp@comune.trento.it
  phone: 0461884111
  url: https://www.comune.trento.it/Citta/Come-orientarsi/Parcheggi
  street: Via Belenzani 19
  town: Trento
  postcode: 38122
  country: Italy
  
- origin: [FBK-Rovereto]
  id: Municipality of Rovereto
  name: Municipality of Rovereto
  email: urp@comune.rovereto.tn.it
  phone: 0464452111
  url: https://www.comune.rovereto.tn.it/Servizi/Sosta-e-parcheggi
  street: Piazza Podestà 11
  town: Rovereto
  postcode: 38068
  country: Italy
  
- origin: [A22]
  id: A22
  name: A22
  email: a22@autobrennero.it
  phone: 0461212611
  url: https://www.autobrennero.it/it/in-viaggio/sosta-e-servizi/aree-di-servizio/
  street: Via Berlino 10
  town: Trento
  postcode: 38121
  country: Italy
  
- origin: 
    - bicincitta
    - skidata
  id: STA
  name: STA
  email: info@sta.bz.it
  phone: 0471312888
  url: https://www.sta.bz.it
  street: Via dei Conciapelli 60
  town: Bolzano
  postcode: 39100
  country: Italy
  
- origin:
    - "1ucCQzAVGmvyRpeq-lIPffALQaWcG4LfPakc2mjt79fY"
    - ALPERIA
    - DRIWE
    - IIT
    - route220
  id: dummy-echarging
  name: dummy-echarging
  email: info@opendatahub.com
  phone: 12345667
  url: https://opendatahub.com
  street: Via The Mars Volta
  town: Bolzano
  postcode: 39100
  country: Italy
  